### ISSUE TITLE
Extra resistors can be removed in OMODRI_Support

### ISSUE THREAD

**Issue by Jmanhes** [open-dynamic-robot-initiative/open-motor-driver-initiative#3]
In OMODRI_Support, R193/R194 are connected to U23.
According to CDCLVC1104 datasheet https://www.ti.com/lit/ds/symlink/cdclvc1104.pdf?ts=1590417975450, page 10/32, Table 1 : output logic table.
If 1G=L =>Yn=L whatever CLKin
if 1G=H => Yn=CLKin
So R194/R193 can be removed and pin can by tied to VDD_3V3

**Comment by nswdc** [comment]
Closed by comit ba2ab1a811792042321e827a74f1fd63dcaec834
