### ISSUE TITLE
firmware

### ISSUE THREAD

**Issue by 1027743011** [open-dynamic-robot-initiative/open-motor-driver-initiative#5]
HI!
     I would like to thank you all the effort that you put on this project and i want to make a  robot by myself.
     I noticed that the firmware is "temporarily hosted in this private repository: https://gitlab.laas.fr/open-dynamic-robot-initiative/omodri".And i cant  connect  the website. I would like to kindly ask you whether you can also share that project.
      Thank you in advance.

**Comment by HanTop310** [comment]
Can't access the gitlab aswell

**Comment by jviereck** [comment]
Hi, sorry for running into this. The firmware is available from here:

 https://github.com/open-dynamic-robot-initiative/udriver_firmware/tree/master/firmware

**Comment by thomasfla** [comment]
The firmware is now pushed on master board, without any dependency to close source library
